In [1]:
import numpy as np
import pandas as pd

arr = [12, 24, 36, 48, 60, 72]

print("One-Dimensional Array:", arr)
print("\nIndexing:")
print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])
print("\nSlicing:")
print("Elements from index 1 to 4:", arr[1:5])
print("\nStart, Stop and Step:")
print("Start=0, Stop=6, Step=2:", arr[0:6:2])
print("Start=1, Stop=6, Step=2:", arr[1:6:2])
print("\nReverse Array:")
print(arr[::-1])

arr2 = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

print("\n\nTwo-Dimensional Array:")
print(arr2)
print("\nIndexing:")
print("First element:", arr2[0, 0])
print("Element at row 2, column 3:", arr2[1, 2])
print("\nSlicing:")
print("First two rows:")
print(arr2[0:2, :])
print("First two columns:")
print(arr2[:, 0:2])
print("\nStart, Stop and Step:")
print("Every alternate row:")
print(arr2[0:3:2])
print("Every alternate column:")
print(arr2[:, 0:3:2])
print("\nReverse 2-D Array:")
print(arr2[::-1, ::-1])

a = np.array([15, 30, 45, 60, 75])
b = np.array([5, 10, 15, 20, 25])

print("\n\nNumPy Operations:")
print("Array A:", a)
print("Array B:", b)
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Sum of A:", np.sum(a))
print("Maximum of A:", np.max(a))
print("Minimum of A:", np.min(a))
print("Mean of A:", np.mean(a))

data = {
    "Name": ["Mahanthesh", "Diganth", "Afzal", "Skanda", "Nandeesh"],
    "Marks": [91, 86, 97, 79, 88],
    "Age": [20, 21, 19, 22, 20]
}

df = pd.DataFrame(data)

print("\n\nPandas Operations:")
print("\nDataFrame:")
print(df)
print("\nName Column:")
print(df["Name"])
print("\nFirst three rows:")
print(df.iloc[0:3])
print("\nAverage Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())
print("\nData sorted by Marks:")
print(df.sort_values("Marks"))
print("\nStudents with marks greater than 80:")
print(df[df["Marks"] > 80])

One-Dimensional Array: [12, 24, 36, 48, 60, 72]

Indexing:
First element: 12
Third element: 36
Last element: 72

Slicing:
Elements from index 1 to 4: [24, 36, 48, 60]

Start, Stop and Step:
Start=0, Stop=6, Step=2: [12, 36, 60]
Start=1, Stop=6, Step=2: [24, 48, 72]

Reverse Array:
[72, 60, 48, 36, 24, 12]


Two-Dimensional Array:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Indexing:
First element: 2
Element at row 2, column 3: 12

Slicing:
First two rows:
[[ 2  4  6]
 [ 8 10 12]]
First two columns:
[[ 2  4]
 [ 8 10]
 [14 16]]

Start, Stop and Step:
Every alternate row:
[[ 2  4  6]
 [14 16 18]]
Every alternate column:
[[ 2  6]
 [ 8 12]
 [14 18]]

Reverse 2-D Array:
[[18 16 14]
 [12 10  8]
 [ 6  4  2]]


NumPy Operations:
Array A: [15 30 45 60 75]
Array B: [ 5 10 15 20 25]
Addition: [ 20  40  60  80 100]
Subtraction: [10 20 30 40 50]
Multiplication: [  75  300  675 1200 1875]
Division: [3. 3. 3. 3. 3.]
Sum of A: 225
Maximum of A: 75
Minimum of A: 15
Mean of A: 45.0


Pandas Operations:

DataFr